// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package orm

import (
	"context"
)

type Querier interface {
	GetWebsites(ctx context.Context) ([]Website, error)
	UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error)
	UpsertWebsite(ctx context.Context, url string) (Website, error)
}

var _ Querier = (*Queries)(nil)
